MATRIX/GILTI/urls.py
from django.urls import path
from . import views

app_name = 'GILTI'
urlpatterns = [
    path('', views.ClientView.as_view(), name='clientview'),
    path('sub<pk>', views.SubView.as_view(), name='subview'),
    path('sub-<pk>/detail', views.SubDetail.as_view(), name='subdetail'),
    path('<int:client_id>', views.ClientDelete, name='clientdelete'),
    path('upclient/<pk>', views.ClientUpdate.as_view(), name='updateclient'),
    path('<int:client_id>/<pk>', views.SubDelete, name='subdelete'),
    path('createclient', views.ClientCreate, name='createclient'),
    path('createsub/loc<int:client_id>', views.SubCreate, name='createsub'),
    path('updatesub/<pk>', views.SubUpdate.as_view(), name='updatesub'),
]

MATRIX/MATRIX/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'GILTI'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('GILTI/', include('GILTI.urls')),
]

MATRIX/GILTI/models.py
from django.db import models
import datetime
from django.urls import reverse_lazy, reverse


class Client(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    year_end = models.DateField(blank=True, default=datetime.date.today)
    exp_alloc = models.FloatField(default=0)
    US_Rate = models.FloatField(default=0)
    tax_inc = models.FloatField(default=0)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('GILTI:clientview')

class Subsidiary(models.Model):
    id = models.AutoField(primary_key=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    country = models.CharField(max_length=15)
    ownership = models.FloatField(default=1.0)
    ref = models.CharField(max_length=10)
    #FINANCIAL MODEL
    gross_income = models.FloatField(default=0)
    eci = models.FloatField(default=0)
    sub_f = models.FloatField(default=0)
    rp_div = models.FloatField(default=0)
    for_tax = models.FloatField(default=0)
    qbai = models.FloatField(default=0)
    int_exp = models.FloatField(default=0)


    def get_absolute_url(self):
        return reverse('GILTI:subdetail', kwargs={'pk':self.client.id})
    

MATRIX/GILTI/views.py
from django.shortcuts import render, redirect, reverse
from django.views import generic
from django.http import HttpResponseRedirect
from .models import * 
#import pandas as pd
#from django_pandas.io import read_frame
import datetime
from math import ceil

# Create your views here.

class ClientView(generic.ListView):
    template_name = 'GILTI/clientview.html'
    
    def get_queryset(self):
        client_list = Client.objects.all()
        
        return client_list

def ClientCreate(*args, **kwargs):
    c = Client(name='')
    c.save()
    return HttpResponseRedirect(reverse('GILTI:updateclient', args=[c.id]))


class ClientUpdate(generic.UpdateView):
    model = Client
    fields = '__all__'
    template_name = 'GILTI/updateclient.html'



def ClientDelete(*args, **kwargs):

    Client.objects.filter(id=kwargs['client_id']).delete()
    return HttpResponseRedirect('/GILTI')
    

    
class SubView(generic.DetailView):
    model = Client
    template_name = 'GILTI/subview.html'

    def get_context_data(self, **kwargs):
        client = kwargs['object']


        sub_list = Subsidiary.objects.filter(client_id=client.id)


        data_fields = [
            'Gross Income over deductions (including taxes)',
            'CFC Exclusions - ECI',
            'CFC Exclusions - Subpart F',
            'CFC Exclusions - Related Party Dividends',
            'CFC Subtotal * Ownership',
            'Tested Loss',
            'Net CFC Tested Income',
            'Tested Foreign Income Taxes',
            'Qualified Business Asset Investment',
            '10% of QBAI',
            'Interest Expense that reduced tested income and corresponding income not included in tested income',
            'Tested Income',
            'CFC Exclusions - ECI',
            'CFC Exclusions - Subpart F',
            'CFC Exclusions - Related Party Dividends',
            'CFC Subtotal * Ownership',
            'Tested Loss',
            'Net CFC Tested Income',
            'Tested Foreign Income Taxes',
            'Qualified Business Asset Investment',
            '10% of QBAI',
            'Interest Expense that reduced tested income and corresponding income not included in tested income',
            'Net deemed tangible income',
            'GILTI',
            'Inclusion percentage',
            'Deemed paid credit before 20% haircut',
            'Deemed paid credit after 20% haircut',
            'Taxable Income before GILTI and NOLs',
            'Grossed up GILTI',
            'Net Operating Loss Deduction',
            'Net GILTI',
            '50% Deduction',
            'Taxable income before credit and expense allocation',
            'Expense allocation to GILTI basket',
            'GILTI for FTC Limitation',
            'FTC Limitation',
            'US tax before credit',
            'Foreign Tax Credit',
            'US Tax on GILTI',
            'Foreign Effective Tax rate on tested income',
            'U.S. effective rate',
            'Taxable Income before GILTI and NOLs',
            'Net Operating Loss Available',
            'Amount used for Taxable Income + GILTI',
            'Net Operating Loss Carryforward',
        ]

        context = {
            'sub_list':sub_list,
            'client':client,
            'fields':data_fields,
        }

        return context

class SubDetail(generic.DetailView):
    model = Client
    template_name = 'GILTI/subdetail.html'

    def get_context_data(self, **kwargs):
        client = kwargs['object']
        numFields = []
        sub_data=[]

        data_fields = [
            'Gross Income over deductions (including taxes)',
            'CFC Exclusions - ECI',
            'CFC Exclusions - Subpart F',
            'CFC Exclusions - Related Party Dividends',
            'CFC Subtotal * Ownership',
            'Tested Loss',
            'Net CFC Tested Income',
            'Tested Foreign Income Taxes',
            'Qualified Business Asset Investment',
            '10% of QBAI',
            'Interest Expense that reduced tested income and corresponding income not included in tested income',
            'Tested Income',
            'CFC Exclusions - ECI',
            'CFC Exclusions - Subpart F',
            'CFC Exclusions - Related Party Dividends',
            'CFC Subtotal * Ownership',
            'Tested Loss',
            'Net CFC Tested Income',
            'Tested Foreign Income Taxes',
            'Qualified Business Asset Investment',
            '10% of QBAI',
            'Interest Expense that reduced tested income and corresponding income not included in tested income',
            'Net deemed tangible income',
            'GILTI',
            'Inclusion percentage',
            'Deemed paid credit before 20% haircut',
            'Deemed paid credit after 20% haircut',
            'Taxable Income before GILTI and NOLs',
            'Grossed up GILTI',
            'Net Operating Loss Deduction',
            'Net GILTI',
            '50% Deduction',
            'Taxable income before credit and expense allocation',
            'Expense allocation to GILTI basket',
            'GILTI for FTC Limitation',
            'FTC Limitation',
            'US tax before credit',
            'Foreign Tax Credit',
            'US Tax on GILTI',
            'Foreign Effective Tax rate on tested income',
            'U.S. effective rate',
            'Taxable Income before GILTI and NOLs',
            'Net Operating Loss Available',
            'Amount used for Taxable Income + GILTI',
            'Net Operating Loss Carryforward',
        ]

        for n in range(0, len(data_fields)):
            data_fields[n] += ':'
            numFields.append(n)

        
        subs = Subsidiary.objects.filter(client_id=client.id)

        us_calc = []
        
        if len(subs) > 0:

            for sub in subs:
                slist = [
                    sub.gross_income,   #0
                    sub.eci,    #1
                    sub.sub_f,  #2
                    sub.rp_div  #3
                ]

                slist.append(slist[0] + slist[1] + slist[2] + slist[3]),    #4
                slist += [
                    0,  #5
                ]

                if sub.gross_income < 0:
                    for i in range(0, 5):
                        slist[i] = 0

                slist += [
                    slist[0] + slist[1] + slist[2] + slist[3],  #6
                    sub.for_tax,    #7
                    sub.qbai    #8
                ]
                slist += [
                    '', #9
                    sub.int_exp,    #10
                ]
                slist += [
                    slist[0]*(sub.ownership/100),  #11
                    slist[1]*(sub.ownership/100),   #12
                    slist[2]*(sub.ownership/100),   #13
                    slist[3]*(sub.ownership/100)   #14
                ]

                

                if sub.gross_income < 0:
                    for i in range(11, 15):
                        slist[i] = 0

                    slist[5] = sub.gross_income
                    slist[6] = slist[5]
                    #slist[16] = slist[11]
                    #slist[17] = slist[11]

                slist += [
                    slist[14] + slist[13] + slist[12] + slist[11],   #15
                    sub.gross_income *(sub.ownership/100),    #16
                ]

                if sub.gross_income < 0:
                    slist[15] = 0
                else:
                    slist[16] = 0

                slist += [
                    slist[15] + slist[16], #17
                    slist[7] * (sub.ownership/100),   #18
                    #slist[2]*(sub.ownership/100) + slist[3]*(sub.ownership/100),    #19
                    #slist[7]*(sub.ownership/100),    #20
                    slist[8]*(sub.ownership/100),   #19
                    '', #20
                    slist[10]*(sub.ownership/100),    #21

                ]

                
                sub_data.append(slist)

            gross = 0
            eci = 0
            subf = 0
            rpdiv = 0
            subtot = 0
            loss = 0
            CFCTInc = 0
            forinc = 0
            qbai = 0
            int_exp = 0
            tinc = 0
            a = 0
            b = 0
            c = 0
            d = 0
            e = 0
            f = 0
            g = 0
            h = 0

            for sub in sub_data:
                gross += sub[0] #0
                eci += sub[1]   #1
                subf += sub[2]  #2
                rpdiv += sub[3] #3
                subtot += sub[4]    #4
                loss += sub[5]  #5
                CFCTInc += sub[6]   #6
                forinc = 0  #7
                qbai += sub[8]  #8
                int_exp += sub[10]  #10
                tinc += sub[11] #11
                a += sub[12]    #12
                b += sub[13]    #13
                c += sub[14]    #14
                d += sub[15]    #15
                e += sub[16]    #16
                f += sub[17]    #17
                g += sub[19]    #19
                h += sub[21]    #21

            us_calc.extend((gross, eci, subf, rpdiv, subtot, loss, CFCTInc, forinc,
                            qbai, (qbai/10), int_exp, tinc, a, b, c, d, e, f, 0, g, g/10, h))

            if us_calc[20] - us_calc[21] <= 1:  #22
                us_calc.append(0)
            else:
                us_Calc.append(us_calc[20] - us_calc[21])

            if us_calc[17] - us_calc[22] < 0:   #23
                us_calc.append(0)
            else:
                us_calc.append(us_calc[17] - us_calc[22])
            if us_calc[15] == 0:
                us_calc.append(0)
            elif us_calc[23]/us_calc[15] <= 1:    #24
                us_calc.append((us_calc[23]/us_calc[15]) * 100)
            else:
                us_calc.append('ERROR')

            us_calc.extend((0, 0, client.tax_inc, us_calc[23], 0))

            if (us_calc[27] + us_calc[28]) <= 0: #30

MATRIX/GILTI/templates/GILTI/clientview.html
<style>

div.delete{
    color: red;
    text-align: right;

}

.margin{

    margin-left: 4%

}



</style>

Clients:
<br>
<div>
<table>
{% for client in client_list %}
    <div>
        <tr>
        <td><a href='{% url "GILTI:subdetail" client.id %}'>{{client}}</a></td>
        <td><a href='{% url "GILTI:updateclient" client.id %}' style="color: blue;">Edit Client</a></td>
        <td><a href='{% url "GILTI:clientdelete" client.id %}' style="color: red;">DELETE</a></td>
        </tr>
    </div>
{% endfor %}
</table>
<br>

<a href='{% url "GILTI:createclient" %}' style="color: green;">Add Client</a>

MATRIX/GILTI/templates/GILTI/subdetail.html
{% if subs %}

<table border='1'>
        <tr>

            <td></td>
            {% for sub in subs %}
                <td><a href='{% url "GILTI:subdelete" sub.client_id sub.id %}' style="color: red;">DELETE</a></td>
            {% endfor %}
            <td></td>
            <td><a href='{% url "GILTI:createsub" subs.0.client_id %}' style="color: green;"> Add Subsidiary </a></td>


        </tr>


        <tr>

            <td>CLient</td>
            {% for sub in subs %}
                <td><a href='{% url "GILTI:updatesub" sub.id %}' style="color: blue;">{{sub.name}}</a></td>
            {% endfor %}

            <td>US Calculation</td>

        </tr>

        <tr>
            <td>Gross Income over deductions (including taxes):</td>
                {% for sub in sub_data %}
                    <td>{{sub.0}}</td>
                {% endfor %}
        </tr>

        <tr>
                <td>CFC Exclusions - ECI'</td>
                    {% for sub in sub_data %}
                        <td>{{sub.1}}</td>
                    {% endfor %}
        </tr>

        <tr>
            <td>CFC Exclusions - Subpart F</td>
                {% for sub in sub_data %}
                    <td>{{sub.2}}</td>
                {% endfor %}
        </tr>

        <tr>
            <td>CFC Exclusions - Related Party Dividends</td>
                {% for sub in sub_data %}
                    <td>{{sub.3}}</td>
                {% endfor %}
        </tr>

        <tr>
                <td>CFC Subtotal * Ownership</td>
                    {% for sub in sub_data %}
                        <td>{{sub.4}}</td>
                    {% endfor %}
        </tr>
    
        <tr>
                    <td>Tested Loss</td>
                        {% for sub in sub_data %}
                            <td>{{sub.5}}</td>
                        {% endfor %}
        </tr>
    
        <tr>
                <td>Net CFC Tested Income</td>
                    {% for sub in sub_data %}
                        <td>{{sub.6}}</td>
                    {% endfor %}
        </tr>
    
        <tr>
                <td>Tested Foreign Income Taxes</td>
                    {% for sub in sub_data %}
                        <td>{{sub.7}}</td>
                    {% endfor %}
        </tr>

        <tr>
                    <td>Qualified Business Asset Investment</td>
                        {% for sub in sub_data %}
                            <td>{{sub.8}}</td>
                        {% endfor %}
        </tr>
        
        <tr>
                        <td>10% of QBAI</td>
                            {% for sub in sub_data %}
                                <td>{{sub.9}}</td>
                            {% endfor %}
        </tr>
        
        <tr>
                    <td>Interest Expense that reduced tested income and corresponding income not included in tested income</td>
                        {% for sub in sub_data %}
                            <td>{{sub.10}}</td>
                        {% endfor %}
        </tr>
        
        <tr>
                    <td>Tested Income</td>
                        {% for sub in sub_data %}
                            <td>{{sub.11}}</td>
                        {% endfor %}
        </tr>

        <tr>
                        <td>CFC Exclusions - ECI</td>
                            {% for sub in sub_data %}
                                <td>{{sub.12}}</td>
                            {% endfor %}
        </tr>
            
        <tr>
                            <td>CFC Exclusions - Subpart F</td>
                                {% for sub in sub_data %}
                                    <td>{{sub.13}}</td>
                                {% endfor %}
        </tr>
            
        <tr>
                        <td>CFC Exclusions - Related Party Dividends</td>
                            {% for sub in sub_data %}
                                <td>{{sub.14}}</td>
                            {% endfor %}
        </tr>
            
        <tr>
                        <td>CFC Subtotal * Ownership</td>
                            {% for sub in sub_data %}
                                <td>{{sub.15}}</td>
                            {% endfor %}
        </tr>

        <tr>
                <td>Tested Loss</td>
                    {% for sub in sub_data %}
                        <td>{{sub.16}}</td>
                    {% endfor %}
        </tr>
    
        <tr>
                    <td>Net CFC Tested Income</td>
                        {% for sub in sub_data %}
                            <td>{{sub.17}}</td>
                        {% endfor %}
        </tr>
    
        <tr>
                <td>Tested Foreign Income Taxes</td>
                    {% for sub in sub_data %}
                        <td>{{sub.18}}</td>
                    {% endfor %}
        </tr>
    
        <tr>
                <td>Qualified Business Asset Investment</td>
                    {% for sub in sub_data %}
                        <td>{{sub.19}}</td>
                    {% endfor %}
        </tr>

        <tr>
                <td>10% of QBAI</td>
                    {% for sub in sub_data %}
                        <td>{{sub.20}}</td>
                    {% endfor %}
        </tr>
    
        <tr>
                    <td>Interest Expense that reduced tested income and corresponding income not included in tested income</td>
                        {% for sub in sub_data %}
                            <td>{{sub.21}}</td>
                        {% endfor %}
        </tr>
    
        <tr>
                <td>Net deemed tangible income</td>
                    {% for sub in sub_data %}
                        <td>{{sub.22}}</td>
                    {% endfor %}
        </tr>
    
        <tr>
                <td>GILTI</td>
                    {% for sub in sub_data %}
                        <td>{{sub.23}}</td>
                    {% endfor %}
        </tr>

        <tr>
                    <td>Inclusion percentage</td>
                        {% for sub in sub_data %}
                            <td>{{sub.24}}</td>
                        {% endfor %}
        </tr>
        
        <tr>
                        <td>Deemed paid credit before 20% haircut</td>
                            {% for sub in sub_data %}
                                <td>{{sub.25}}</td>
                            {% endfor %}
        </tr>
        
        <tr>
                    <td>Deemed paid credit after 20% haircut</td>
                        {% for sub in sub_data %}
                            <td>{{sub.26}}</td>
                        {% endfor %}
        </tr>
        
        <tr>
                    <td>Taxable Income before GILTI and NOLs</td>
                        {% for sub in sub_data %}
                            <td>{{sub.27}}</td>
                        {% endfor %}
        </tr>

        <tr>
                        <td>Grossed up GILTI</td>
                            {% for sub in sub_data %}
                                <td>{{sub.28}}</td>
                            {% endfor %}
        </tr>
            
        <tr>
                            <td>Net Operating Loss Deduction</td>
                                {% for sub in sub_data %}
                                    <td>{{sub.29}}</td>
                                {% endfor %}
        </tr>
            
        <tr>
                        <td>Net GILTI</td>
                            {% for sub in sub_data %}
                                <td>{{sub.30}}</td>
                            {% endfor %}
        </tr>
            
        <tr>
                        <td>50% Deduction</td>
                            {% for sub in sub_data %}
                                <td>{{sub.31}}</td>
                            {% endfor %}
        </tr>

        <tr>
                            <td>Taxable income before credit and expense allocation</td>
                                {% for sub in sub_data %}
                                    <td>{{sub.32}}</td>
                                {% endfor %}
        </tr>
                
        <tr>
                                <td>Expense allocation to GILTI basket</td>
                                    {% for sub in sub_data %}
                                        <td>{{sub.33}}</td>
                                    {% endfor %}
        </tr>
                
        <tr>
                            <td>GILTI for FTC Limitation</td>
                                {% for sub in sub_data %}
                                    <td>{{sub.34}}</td>
                                {% endfor %}
        </tr>
                
        <tr>
                            <td>FTC Limitation</td>
                                {% for sub in sub_data %}
                                    <td>{{sub.35}}</td>
                                {% endfor %}
        </tr>

        <tr>
                                <td>US tax before credit</td>
                                    {% for sub in sub_data %}
                                        <td>{{sub.36}}</td>
                                    {% endfor %}
        </tr>
                    
        <tr>
                                    <td>Foreign Tax Credit</td>
                                        {% for sub in sub_data %}
                                            <td>{{sub.37}}</td>
                                        {% endfor %}
        </tr>
                    
        <tr>
                                <td>US Tax on GILTI</td>
                                    {% for sub in sub_data %}
                                        <td>{{sub.38}}</td>
                                    {% endfor %}
        </tr>
                    
        <tr>
                                <td>Foreign Effective Tax rate on tested income</td>
                                    {% for sub in sub_data %}
                                        <td>{{sub.39}}</td>
                                    {% endfor %}
        </tr>


        <tr>
                                    <td>U.S. effective rate</td>
                                        {% for sub in sub_data %}
                                            <td>{{sub.40}}</td>
                                        {% endfor %}
        </tr>
                        
        <tr>
                                        <td>Taxable Income before GILTI and NOLs</td>
                                            {% for sub in sub_data %}
                                                <td>{{sub.41}}</td>
                                            {% endfor %}
        </tr>
                        
        <tr>
                                    <td>Net Operating Loss Available</td>
                                        {% for sub in sub_data %}
                                            <td>{{sub.42}}</td>
                                        {% endfor %}
        </tr>
                        
        <tr>
                                    <td>Amount used for Taxable Income + GILTI</td>
                                        {% for sub in sub_data %}
                                            <td>{{sub.43}}</td>
                                        {% endfor %}
        </tr>

        <tr>
                <td>Net Operating Loss Carryforward</td>
                    {% for sub in sub_data %}
                        <td>{{sub.44}}</td>
                    {% endfor %}
        </tr>
</table>
{% endif %}

nothing to show

{{client.name}}
<a href='{% url "GILTI:createsub" client.id %}' style="color: green;"> Add Subsidiary </a>

MATRIX/GILTI/templates/GILTI/subview.html
{% if sub_list %}

Subsidiarys:
<br>
<table>
{% for subsidiary in sub_list %}
    <div>
    <tr>    
        <td><a href='{% url "GILTI:subdetail" subsidiary.id %}'>{{subsidiary.name}}</a></td>
        <td><a href='{% url "GILTI:updatesub" subsidiary.id %}' style="color: blue;">Edit subsidiary</a></td>
        <td><a href='{% url "GILTI:subdelete" subsidiary.client_id subsidiary.id %}' style="color: red;">DELETE</a></td>
    </tr>
    </div>
{% endfor %}
</table>
{% else %}

<p>No Subsidiarys</p>

{% endif %}
<br>
<a href='{% url "GILTI:createsub" client.id %}' style="color: green;"> Add Subsidiary </a>

MATRIX/GILTI/templates/GILTI/updateclient.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>